# Generated by Django 5.2.4 on 2025-07-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_completed_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expand',
            field=models.BooleanField(default=False),
        ),
    ]
