# Generated by Django 5.2.4 on 2025-07-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_task_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-priority']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='expand',
        ),
    ]
